name: manual-ci

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Nuget package version'
        required: true
        type: string

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.5
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release -p:Version=${{ inputs.version }}
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release 
    - name: Pack ConfigurationExtensions
      run: dotnet pack --no-build --configuration Release ConfigurationExtensions/ConfigurationExtensions.csproj --output . -p:PackageVersion=${{ inputs.version }}
    - name: PushNuget
      run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
